version: '3.8'

services:
  app:
    build: 
      context: .
      target: builder
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd
    environment:
      - CONFIG_PATH=/app/configs/server-config.yaml
      - DATABASE_URL=postgres://booking_user:booking_pass@postgres:5432/booking_db?sslmode=disable

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@booking.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres

volumes:
  postgres_data:
