// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: appointments.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const CheckClientAppointmentConflict = `-- name: CheckClientAppointmentConflict :one

SELECT EXISTS(
    SELECT 1 FROM appointments a
    INNER JOIN client_appointments ca ON ca.appointment_id = a.id
    WHERE ca.client_id = $1 
    AND a.professional_id = $2 
    AND a.start_time = $3 
    AND a.status IN ('pending', 'confirmed')
) as has_conflict
`

type CheckClientAppointmentConflictParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	ProfessionalID uuid.UUID `json:"professional_id"`
	StartTime      time.Time `json:"start_time"`
}

// -- name: GetAppointmentsByProfessionalAndDate :many
// SELECT * FROM appointments
// WHERE professional_id = $1
//
//	AND DATE(start_time) = $2
//	AND type = 'appointment' or type = 'unavailable'
//	AND status not in ('cancelled', 'pending')
//
// ORDER BY start_time ASC;
func (q *Queries) CheckClientAppointmentConflict(ctx context.Context, arg *CheckClientAppointmentConflictParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, CheckClientAppointmentConflict, arg.ClientID, arg.ProfessionalID, arg.StartTime)
	var has_conflict bool
	err := row.Scan(&has_conflict)
	return has_conflict, err
}

const ConfirmAppointmentById = `-- name: ConfirmAppointmentById :exec

UPDATE appointments
SET status = 'confirmed', updated_at = NOW()
WHERE id = $1
`

// -- name: CreateAppointmentWithDetails :one
// WITH new_appointment AS (
//
//	INSERT INTO appointments (type, professional_id, start_time, end_time, status, description)
//	VALUES ('appointment', $1, $2, $3, $4, 'pending', $5)
//	RETURNING *
//
// )
// SELECT
//
//	na.start_time,
//	na.end_time,
//	na.description,
//	c.first_name as client_first_name,
//	c.last_name as client_last_name,
//	p.chat_id as professional_chat_id,
//	p.locale as professional_locale
//
// FROM new_appointment na
// LEFT JOIN clients c ON c.id = na.client_id
// LEFT JOIN professionals p ON p.id = na.professional_id;
func (q *Queries) ConfirmAppointmentById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, ConfirmAppointmentById, id)
	return err
}

const CountClientAppointmentsByAppointmentID = `-- name: CountClientAppointmentsByAppointmentID :one
SELECT COUNT(*)
FROM client_appointments
WHERE appointment_id = $1
`

func (q *Queries) CountClientAppointmentsByAppointmentID(ctx context.Context, appointmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountClientAppointmentsByAppointmentID, appointmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountClientAppointmentsWithStatus = `-- name: CountClientAppointmentsWithStatus :one
SELECT COUNT(*)
FROM appointments a
WHERE
    a.id in (
        select appointment_id from client_appointments where client_id = $1
    )
  AND a.status = $2
  AND a.start_time > NOW()
  AND a.type != 'unavailable'
`

type CountClientAppointmentsWithStatusParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CountClientAppointmentsWithStatus(ctx context.Context, arg *CountClientAppointmentsWithStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountClientAppointmentsWithStatus, arg.ClientID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountPreviousAppointmentsByClientID = `-- name: CountPreviousAppointmentsByClientID :one
SELECT COUNT(DISTINCT a.id)
FROM appointments a
WHERE a.id IN (
    SELECT DISTINCT(appointment_id)
    FROM client_appointments ca
    WHERE ca.client_id = $1
)
  AND a.status = 'confirmed'
  AND a.end_time < NOW()
`

func (q *Queries) CountPreviousAppointmentsByClientID(ctx context.Context, clientID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPreviousAppointmentsByClientID, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePersonalAppointment = `-- name: CreatePersonalAppointment :one
INSERT INTO appointments (type, professional_id, start_time, end_time, status)
VALUES ('personal', $1, $2, $3, 'pending')
RETURNING id, type, professional_id, start_time, end_time, status, created_at, updated_at
`

type CreatePersonalAppointmentParams struct {
	ProfessionalID uuid.UUID `json:"professional_id"`
	StartTime      time.Time `json:"start_time"`
	EndTime        time.Time `json:"end_time"`
}

type CreatePersonalAppointmentRow struct {
	ID             uuid.UUID `json:"id"`
	Type           string    `json:"type"`
	ProfessionalID uuid.UUID `json:"professional_id"`
	StartTime      time.Time `json:"start_time"`
	EndTime        time.Time `json:"end_time"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) CreatePersonalAppointment(ctx context.Context, arg *CreatePersonalAppointmentParams) (*CreatePersonalAppointmentRow, error) {
	row := q.db.QueryRowContext(ctx, CreatePersonalAppointment, arg.ProfessionalID, arg.StartTime, arg.EndTime)
	var i CreatePersonalAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProfessionalID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const CreateUnavailableAppointment = `-- name: CreateUnavailableAppointment :exec

INSERT INTO appointments (type, professional_id, start_time, end_time, status, description)
VALUES ('unavailable', $1, $2, $3, 'confirmed', $4)
`

type CreateUnavailableAppointmentParams struct {
	ProfessionalID uuid.UUID      `json:"professional_id"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Description    sql.NullString `json:"description"`
}

// -- name: CancelAppointmentByClientWithDetails :one
// WITH updated_appointment AS (
//
//	UPDATE appointments
//	SET
//	    status = 'cancelled',
//	    cancellation_reason = $3,
//	    cancelled_by_client_id = $2,
//	    updated_at = NOW()
//	WHERE appointments.id = $1
//	AND client_id = $2
//	AND status IN ('pending', 'confirmed')
//	RETURNING *
//
// )
// SELECT
//
//	ua.start_time,
//	ua.end_time,
//	ua.cancellation_reason,
//	ua.description,
//	c.first_name as client_first_name,
//	c.last_name as client_last_name,
//	p.chat_id as professional_chat_id,
//	p.locale as professional_locale
//
// FROM updated_appointment ua
// LEFT JOIN clients c ON c.id = ua.client_id
// LEFT JOIN professionals p ON p.id = ua.professional_id;
func (q *Queries) CreateUnavailableAppointment(ctx context.Context, arg *CreateUnavailableAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, CreateUnavailableAppointment,
		arg.ProfessionalID,
		arg.StartTime,
		arg.EndTime,
		arg.Description,
	)
	return err
}

const DeleteAppointmentById = `-- name: DeleteAppointmentById :exec
DELETE FROM appointments
WHERE id = $1
`

func (q *Queries) DeleteAppointmentById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteAppointmentById, id)
	return err
}

const GetAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, type, professional_id, start_time, end_time, status, description, created_at, updated_at FROM appointments
WHERE id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (*Appointment, error) {
	row := q.db.QueryRowContext(ctx, GetAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProfessionalID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetAppointmentClientsByAppointmentID = `-- name: GetAppointmentClientsByAppointmentID :many
SELECT c.id, c.first_name, c.last_name, c.chat_id as client_chat_id, c.locale as client_locale
FROM client_appointments ca
JOIN clients c ON c.id = ca.client_id
WHERE ca.appointment_id = $1
`

type GetAppointmentClientsByAppointmentIDRow struct {
	ID           uuid.UUID     `json:"id"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	ClientChatID sql.NullInt64 `json:"client_chat_id"`
	ClientLocale string        `json:"client_locale"`
}

func (q *Queries) GetAppointmentClientsByAppointmentID(ctx context.Context, appointmentID uuid.UUID) ([]*GetAppointmentClientsByAppointmentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAppointmentClientsByAppointmentID, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAppointmentClientsByAppointmentIDRow{}
	for rows.Next() {
		var i GetAppointmentClientsByAppointmentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ClientChatID,
			&i.ClientLocale,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAppointmentInfoByAppointmentID = `-- name: GetAppointmentInfoByAppointmentID :one
SELECT start_time, end_time FROM appointments a
WHERE a.id = $1
`

type GetAppointmentInfoByAppointmentIDRow struct {
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) GetAppointmentInfoByAppointmentID(ctx context.Context, id uuid.UUID) (*GetAppointmentInfoByAppointmentIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetAppointmentInfoByAppointmentID, id)
	var i GetAppointmentInfoByAppointmentIDRow
	err := row.Scan(&i.StartTime, &i.EndTime)
	return &i, err
}

const GetAppointmentWithDetails = `-- name: GetAppointmentWithDetails :one
SELECT 
    a.id,
    a.type,
    a.professional_id,
    a.start_time,
    a.end_time,
    a.status,
    a.created_at,
    a.updated_at,
    c.id as client_id,
    c.first_name as client_first_name,
    c.last_name as client_last_name,
    c.chat_id as client_chat_id,
    c.locale as client_locale,
    p.chat_id as professional_chat_id,
    p.locale as professional_locale
FROM appointments a
LEFT JOIN client_appointments ca ON ca.appointment_id = a.id
LEFT JOIN clients c ON c.id = ca.client_id
LEFT JOIN professionals p ON p.id = a.professional_id
WHERE a.id = $1
`

type GetAppointmentWithDetailsRow struct {
	ID                 uuid.UUID      `json:"id"`
	Type               string         `json:"type"`
	ProfessionalID     uuid.UUID      `json:"professional_id"`
	StartTime          time.Time      `json:"start_time"`
	EndTime            time.Time      `json:"end_time"`
	Status             string         `json:"status"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	ClientID           uuid.UUID      `json:"client_id"`
	ClientFirstName    sql.NullString `json:"client_first_name"`
	ClientLastName     sql.NullString `json:"client_last_name"`
	ClientChatID       sql.NullInt64  `json:"client_chat_id"`
	ClientLocale       sql.NullString `json:"client_locale"`
	ProfessionalChatID sql.NullInt64  `json:"professional_chat_id"`
	ProfessionalLocale sql.NullString `json:"professional_locale"`
}

func (q *Queries) GetAppointmentWithDetails(ctx context.Context, id uuid.UUID) (*GetAppointmentWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, GetAppointmentWithDetails, id)
	var i GetAppointmentWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ProfessionalID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
		&i.ClientFirstName,
		&i.ClientLastName,
		&i.ClientChatID,
		&i.ClientLocale,
		&i.ProfessionalChatID,
		&i.ProfessionalLocale,
	)
	return &i, err
}

const GetAppointmentsByClientWithStatus = `-- name: GetAppointmentsByClientWithStatus :many



SELECT 
    a.id,
    a.start_time,
    a.end_time,
    a.type,
    a.status,
    p.first_name AS professional_first_name,
    p.last_name AS professional_last_name,
    p.chat_id AS professional_chat_id
FROM appointments a
LEFT JOIN professionals p ON p.id = a.professional_id
WHERE
  a.id in (
    select appointment_id from client_appointments where client_id = $1
  )
  AND a.status = $2
  AND a.start_time > NOW()
  AND a.type != 'unavailable'
ORDER BY a.start_time ASC
LIMIT $3 OFFSET $4
`

type GetAppointmentsByClientWithStatusParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Status   string    `json:"status"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetAppointmentsByClientWithStatusRow struct {
	ID                    uuid.UUID      `json:"id"`
	StartTime             time.Time      `json:"start_time"`
	EndTime               time.Time      `json:"end_time"`
	Type                  string         `json:"type"`
	Status                string         `json:"status"`
	ProfessionalFirstName sql.NullString `json:"professional_first_name"`
	ProfessionalLastName  sql.NullString `json:"professional_last_name"`
	ProfessionalChatID    sql.NullInt64  `json:"professional_chat_id"`
}

// -- name: GetAppointmentsByProfessionalWithStatus :many
// SELECT
//
//	a.*,
//	c.id AS client_id,
//	c.first_name AS client_first_name,
//	c.last_name AS client_last_name,
//	c.chat_id AS client_chat_id
//
// FROM appointments a
// LEFT JOIN clients c ON c.id = a.client_id
// WHERE a.professional_id = $1
//
//	AND a.status = $2
//	AND a.start_time > NOW()
//	AND a.type = 'appointment'
//
// ORDER BY a.start_time DESC;
// -- name: CancelAppointmentByProfessionalWithDetails :one
// WITH updated_appointment AS (
//
//	UPDATE appointments
//	SET
//	    status = 'cancelled',
//	    cancellation_reason = $3,
//	    cancelled_by_professional_id = $2,
//	    updated_at = NOW()
//	WHERE appointments.id = $1
//	AND professional_id = $2
//	AND status IN ('pending', 'confirmed')
//	RETURNING *
//
// )
// SELECT
//
//	ua.id,
//	ua.type,
//	ua.professional_id,
//	ua.start_time,
//	ua.end_time,
//	ua.status,
//	ua.cancellation_reason,
//	ua.cancelled_by_professional_id,
//	ua.cancelled_by_client_id,
//	ua.created_at,
//	ua.updated_at,
//	c.id as client_id_full,
//	c.first_name as client_first_name,
//	c.last_name as client_last_name,
//	c.phone_number as client_phone_number,
//	c.chat_id as client_chat_id,
//	c.locale as client_locale,
//	p.id as professional_id_full,
//	p.username as professional_username,
//	p.first_name as professional_first_name,
//	p.last_name as professional_last_name,
//	p.phone_number as professional_phone_number,
//	p.chat_id as professional_chat_id
//
// FROM updated_appointment ua
// LEFT JOIN clients c ON c.id = ua.client_id
// LEFT JOIN professionals p ON p.id = ua.professional_id;
func (q *Queries) GetAppointmentsByClientWithStatus(ctx context.Context, arg *GetAppointmentsByClientWithStatusParams) ([]*GetAppointmentsByClientWithStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAppointmentsByClientWithStatus,
		arg.ClientID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAppointmentsByClientWithStatusRow{}
	for rows.Next() {
		var i GetAppointmentsByClientWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Type,
			&i.Status,
			&i.ProfessionalFirstName,
			&i.ProfessionalLastName,
			&i.ProfessionalChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAppointmentsByProfessionalByDate = `-- name: GetAppointmentsByProfessionalByDate :many
SELECT 
    a.start_time,
    a.end_time
FROM appointments a
WHERE a.professional_id = $1
  AND DATE(a.start_time) = $2
  AND a.status NOT IN ('pending')
ORDER BY a.start_time ASC
`

type GetAppointmentsByProfessionalByDateParams struct {
	ProfessionalID uuid.UUID `json:"professional_id"`
	StartTime      time.Time `json:"start_time"`
}

type GetAppointmentsByProfessionalByDateRow struct {
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) GetAppointmentsByProfessionalByDate(ctx context.Context, arg *GetAppointmentsByProfessionalByDateParams) ([]*GetAppointmentsByProfessionalByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAppointmentsByProfessionalByDate, arg.ProfessionalID, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAppointmentsByProfessionalByDateRow{}
	for rows.Next() {
		var i GetAppointmentsByProfessionalByDateRow
		if err := rows.Scan(&i.StartTime, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPreviousAppointmentsByClientID = `-- name: GetPreviousAppointmentsByClientID :many



SELECT 
    a.id, 
    a.start_time, 
    a.end_time, 
    a.type, 
    p.first_name,
    p.last_name
FROM appointments a
JOIN professionals p ON p.id = a.professional_id
WHERE a.id IN (
    SELECT DISTINCT(appointment_id)
    FROM client_appointments ca
    WHERE ca.client_id = $1
)
  AND a.status = 'confirmed'
  AND a.end_time < NOW()
ORDER BY a.start_time DESC
LIMIT $2 OFFSET $3
`

type GetPreviousAppointmentsByClientIDParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetPreviousAppointmentsByClientIDRow struct {
	ID        uuid.UUID `json:"id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Type      string    `json:"type"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

// -- name: GetPreviousProfessionalAppointmentsByClient :many
// SELECT id, start_time, end_time, description
// FROM appointments
// WHERE client_id = $1
//
//	AND professional_id = $2
//	AND status = 'confirmed'
//	AND end_time < NOW()
//
// ORDER BY start_time DESC;
// -- name: GetPreviousAppointmentsByClientForMonth :many
// SELECT id, start_time, end_time, description
// FROM appointments
// WHERE client_id = sqlc.arg(client_id)
//
//	AND professional_id = sqlc.arg(professional_id)
//	AND status = 'confirmed'
//	AND end_time < NOW()
//	AND DATE_TRUNC('month', start_time) = DATE_TRUNC('month', sqlc.arg(month_date)::date)
//
// ORDER BY start_time DESC;
func (q *Queries) GetPreviousAppointmentsByClientID(ctx context.Context, arg *GetPreviousAppointmentsByClientIDParams) ([]*GetPreviousAppointmentsByClientIDRow, error) {
	rows, err := q.db.QueryContext(ctx, GetPreviousAppointmentsByClientID, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPreviousAppointmentsByClientIDRow{}
	for rows.Next() {
		var i GetPreviousAppointmentsByClientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Type,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProfessionalTimetable = `-- name: GetProfessionalTimetable :many

SELECT 
    a.id,
    a.start_time,
    a.end_time,
    a.description,
    a.type,
    COALESCE(
        ARRAY_AGG(
            c.first_name || ' ' || c.last_name
            ORDER BY c.last_name
        ) FILTER (WHERE c.id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS clients
FROM appointments a
LEFT JOIN client_appointments ca ON ca.appointment_id = a.id
LEFT JOIN clients c ON c.id = ca.client_id
WHERE a.professional_id = $1
  AND a.status = 'confirmed'
  AND DATE(a.start_time) = $2
  AND a.end_time > NOW()
GROUP BY a.id, a.start_time, a.end_time, a.description
ORDER BY a.start_time ASC
`

type GetProfessionalTimetableParams struct {
	ProfessionalID uuid.UUID `json:"professional_id"`
	StartTime      time.Time `json:"start_time"`
}

type GetProfessionalTimetableRow struct {
	ID          uuid.UUID      `json:"id"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
	Clients     []string       `json:"clients"`
}

// -- name: GetProfessionalAppointmentDates :many
// SELECT DISTINCT DATE(start_time) AS appointment_date
// FROM appointments
// WHERE professional_id = $1
//
//	AND type = 'appointment'
//	AND status = 'confirmed'
//	AND start_time >= $2
//	AND start_time < $3
//
// ORDER BY appointment_date ASC;
func (q *Queries) GetProfessionalTimetable(ctx context.Context, arg *GetProfessionalTimetableParams) ([]*GetProfessionalTimetableRow, error) {
	rows, err := q.db.QueryContext(ctx, GetProfessionalTimetable, arg.ProfessionalID, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProfessionalTimetableRow{}
	for rows.Next() {
		var i GetProfessionalTimetableRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Description,
			&i.Type,
			pq.Array(&i.Clients),
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAppointment = `-- name: UpdateAppointment :exec
UPDATE appointments
SET 
    type = COALESCE($2, type),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAppointmentParams struct {
	ID          uuid.UUID      `json:"id"`
	Type        string         `json:"type"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg *UpdateAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAppointment, arg.ID, arg.Type, arg.Description)
	return err
}
