// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clients.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CreateClient = `-- name: CreateClient :one
INSERT INTO clients (first_name, last_name, phone_number, chat_id, created_by, locale)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, chat_id, first_name, last_name, phone_number, created_by, created_at, updated_at, locale
`

type CreateClientParams struct {
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	ChatID      sql.NullInt64  `json:"chat_id"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	Locale      sql.NullString `json:"locale"`
}

func (q *Queries) CreateClient(ctx context.Context, arg *CreateClientParams) (*Client, error) {
	row := q.db.QueryRowContext(ctx, CreateClient,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.ChatID,
		arg.CreatedBy,
		arg.Locale,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
	)
	return &i, err
}

const UpdateClientLocale = `-- name: UpdateClientLocale :exec
UPDATE clients
SET locale = $2
WHERE id = $1
`

type UpdateClientLocaleParams struct {
	ID     uuid.UUID      `json:"id"`
	Locale sql.NullString `json:"locale"`
}

func (q *Queries) UpdateClientLocale(ctx context.Context, arg *UpdateClientLocaleParams) error {
	_, err := q.db.ExecContext(ctx, UpdateClientLocale, arg.ID, arg.Locale)
	return err
}
