// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: client_appointments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CreateClientAppointment = `-- name: CreateClientAppointment :exec
INSERT INTO client_appointments (client_id, appointment_id)
VALUES ($1, $2)
`

type CreateClientAppointmentParams struct {
	ClientID      uuid.UUID `json:"client_id"`
	AppointmentID uuid.UUID `json:"appointment_id"`
}

func (q *Queries) CreateClientAppointment(ctx context.Context, arg *CreateClientAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, CreateClientAppointment, arg.ClientID, arg.AppointmentID)
	return err
}
