// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const CreateInvites = `-- name: CreateInvites :exec
WITH a AS (
  SELECT x AS appointment_id, ord
  FROM unnest($1::uuid[]) WITH ORDINALITY AS t(x, ord)
),
b AS (
  SELECT x AS start_time, ord
  FROM unnest($2::timestamptz[]) WITH ORDINALITY AS t(x, ord)
),
c AS (
  SELECT x AS end_time, ord
  FROM unnest($3::timestamptz[]) WITH ORDINALITY AS t(x, ord)
),
d AS (
  SELECT x AS client_id, ord
  FROM unnest($4::uuid[]) WITH ORDINALITY AS t(x, ord)
),
e AS (
  SELECT x AS description, ord
  FROM unnest($5::text[]) WITH ORDINALITY AS t(x, ord)
),
f AS (
  SELECT x AS type, ord
  FROM unnest($6::appointment_type[]) WITH ORDINALITY AS t(x, ord)
),
g AS (
  SELECT x AS professional_name, ord
  FROM unnest($7::text[]) WITH ORDINALITY AS t(x, ord)
)
INSERT INTO invites (appointment_id, start_time, end_time, client_id, description, type, professional_name)
SELECT a.appointment_id, b.start_time, c.end_time, d.client_id, e.description, f.type, g.professional_name
FROM a
JOIN b USING (ord)
JOIN c USING (ord)
JOIN d USING (ord)
JOIN e USING (ord)
JOIN f USING (ord)
JOIN g USING (ord)
`

type CreateInvitesParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []time.Time `json:"column_2"`
	Column3 []time.Time `json:"column_3"`
	Column4 []uuid.UUID `json:"column_4"`
	Column5 []string    `json:"column_5"`
	Column6 []string    `json:"column_6"`
	Column7 []string    `json:"column_7"`
}

func (q *Queries) CreateInvites(ctx context.Context, arg *CreateInvitesParams) error {
	_, err := q.db.ExecContext(ctx, CreateInvites,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		pq.Array(arg.Column5),
		pq.Array(arg.Column6),
		pq.Array(arg.Column7),
	)
	return err
}

const GetClientInvites = `-- name: GetClientInvites :many
SELECT id, appointment_id, start_time, client_id, description, type, professional_name FROM invites
WHERE client_id = $1
`

type GetClientInvitesRow struct {
	ID               uuid.UUID `json:"id"`
	AppointmentID    uuid.UUID `json:"appointment_id"`
	StartTime        time.Time `json:"start_time"`
	ClientID         uuid.UUID `json:"client_id"`
	Description      string    `json:"description"`
	Type             string    `json:"type"`
	ProfessionalName string    `json:"professional_name"`
}

func (q *Queries) GetClientInvites(ctx context.Context, clientID uuid.UUID) ([]*GetClientInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetClientInvites, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetClientInvitesRow{}
	for rows.Next() {
		var i GetClientInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.StartTime,
			&i.ClientID,
			&i.Description,
			&i.Type,
			&i.ProfessionalName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetInvitesByAppointmentIDAndClientIs = `-- name: GetInvitesByAppointmentIDAndClientIs :many
SELECT id, client_id FROM invites
WHERE appointment_id = $1
AND client_id = ANY($2::uuid[])
`

type GetInvitesByAppointmentIDAndClientIsParams struct {
	AppointmentID uuid.UUID   `json:"appointment_id"`
	Column2       []uuid.UUID `json:"column_2"`
}

type GetInvitesByAppointmentIDAndClientIsRow struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetInvitesByAppointmentIDAndClientIs(ctx context.Context, arg *GetInvitesByAppointmentIDAndClientIsParams) ([]*GetInvitesByAppointmentIDAndClientIsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetInvitesByAppointmentIDAndClientIs, arg.AppointmentID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetInvitesByAppointmentIDAndClientIsRow{}
	for rows.Next() {
		var i GetInvitesByAppointmentIDAndClientIsRow
		if err := rows.Scan(&i.ID, &i.ClientID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
