// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID             uuid.UUID      `json:"id"`
	Type           string         `json:"type"`
	ProfessionalID uuid.UUID      `json:"professional_id"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Status         string         `json:"status"`
	Description    sql.NullString `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Client struct {
	ID        uuid.UUID     `json:"id"`
	ChatID    sql.NullInt64 `json:"chat_id"`
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
	Locale    string        `json:"locale"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ClientAppointment struct {
	ID            uuid.UUID `json:"id"`
	ClientID      uuid.UUID `json:"client_id"`
	AppointmentID uuid.UUID `json:"appointment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Invite struct {
	ID               uuid.UUID `json:"id"`
	AppointmentID    uuid.UUID `json:"appointment_id"`
	StartTime        time.Time `json:"start_time"`
	EndTime          time.Time `json:"end_time"`
	ClientID         uuid.UUID `json:"client_id"`
	Description      string    `json:"description"`
	Type             string    `json:"type"`
	ProfessionalName string    `json:"professional_name"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Professional struct {
	ID           uuid.UUID     `json:"id"`
	ChatID       sql.NullInt64 `json:"chat_id"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	Username     string        `json:"username"`
	PasswordHash string        `json:"password_hash"`
	Locale       string        `json:"locale"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type Subscription struct {
	ID             uuid.UUID `json:"id"`
	ClientID       uuid.UUID `json:"client_id"`
	ProfessionalID uuid.UUID `json:"professional_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
