// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: packages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CreatePackage = `-- name: CreatePackage :exec
INSERT INTO packages (client_id, professional_id, issued_at, expires_at, apppointments_number)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePackageParams struct {
	ClientID            uuid.UUID `json:"client_id"`
	ProfessionalID      uuid.UUID `json:"professional_id"`
	IssuedAt            time.Time `json:"issued_at"`
	ExpiresAt           time.Time `json:"expires_at"`
	ApppointmentsNumber int32     `json:"apppointments_number"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg *CreatePackageParams) error {
	_, err := q.db.ExecContext(ctx, CreatePackage,
		arg.ClientID,
		arg.ProfessionalID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ApppointmentsNumber,
	)
	return err
}

const DeactivatePackage = `-- name: DeactivatePackage :exec
UPDATE packages SET deactivated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivatePackage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeactivatePackage, id)
	return err
}

const GetAppintmentNumberByClientIDAndProfessionalID = `-- name: GetAppintmentNumberByClientIDAndProfessionalID :one
SELECT COUNT(*) FROM appointments
WHERE professional_id = $1
AND id IN (SELECT appointment_id FROM client_appointments WHERE client_id = $2)
AND start_time > $3
`

type GetAppintmentNumberByClientIDAndProfessionalIDParams struct {
	ProfessionalID uuid.UUID `json:"professional_id"`
	ClientID       uuid.UUID `json:"client_id"`
	StartTime      time.Time `json:"start_time"`
}

func (q *Queries) GetAppintmentNumberByClientIDAndProfessionalID(ctx context.Context, arg *GetAppintmentNumberByClientIDAndProfessionalIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetAppintmentNumberByClientIDAndProfessionalID, arg.ProfessionalID, arg.ClientID, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetAppointmentsForThePackage = `-- name: GetAppointmentsForThePackage :many
SELECT id, start_time, end_time, type FROM appointments
WHERE id IN (SELECT appointment_id FROM client_appointments WHERE client_id = $1)
and professional_id = $2
and start_time > $3
and end_time < NOW()
`

type GetAppointmentsForThePackageParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	ProfessionalID uuid.UUID `json:"professional_id"`
	StartTime      time.Time `json:"start_time"`
}

type GetAppointmentsForThePackageRow struct {
	ID        uuid.UUID `json:"id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Type      string    `json:"type"`
}

func (q *Queries) GetAppointmentsForThePackage(ctx context.Context, arg *GetAppointmentsForThePackageParams) ([]*GetAppointmentsForThePackageRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAppointmentsForThePackage, arg.ClientID, arg.ProfessionalID, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAppointmentsForThePackageRow{}
	for rows.Next() {
		var i GetAppointmentsForThePackageRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetListOfPackagesByProfessionalID = `-- name: GetListOfPackagesByProfessionalID :many
SELECT p.id, c.first_name, c.last_name, p.issued_at, p.expires_at, p.apppointments_number FROM packages p
LEFT JOIN clients c ON c.id = p.client_id
WHERE professional_id = $1
and deactivated_at is null
`

type GetListOfPackagesByProfessionalIDRow struct {
	ID                  uuid.UUID      `json:"id"`
	FirstName           sql.NullString `json:"first_name"`
	LastName            sql.NullString `json:"last_name"`
	IssuedAt            time.Time      `json:"issued_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	ApppointmentsNumber int32          `json:"apppointments_number"`
}

func (q *Queries) GetListOfPackagesByProfessionalID(ctx context.Context, professionalID uuid.UUID) ([]*GetListOfPackagesByProfessionalIDRow, error) {
	rows, err := q.db.QueryContext(ctx, GetListOfPackagesByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetListOfPackagesByProfessionalIDRow{}
	for rows.Next() {
		var i GetListOfPackagesByProfessionalIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.ApppointmentsNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPackageByClientIDAndProfessionalID = `-- name: GetPackageByClientIDAndProfessionalID :one
SELECT id, client_id, professional_id, issued_at, expires_at, apppointments_number, deactivated_at, created_at, updated_at FROM packages WHERE client_id = $1 AND professional_id = $2
`

type GetPackageByClientIDAndProfessionalIDParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	ProfessionalID uuid.UUID `json:"professional_id"`
}

func (q *Queries) GetPackageByClientIDAndProfessionalID(ctx context.Context, arg *GetPackageByClientIDAndProfessionalIDParams) (*Package, error) {
	row := q.db.QueryRowContext(ctx, GetPackageByClientIDAndProfessionalID, arg.ClientID, arg.ProfessionalID)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ApppointmentsNumber,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetPackageById = `-- name: GetPackageById :one
SELECT id, client_id, professional_id, issued_at, expires_at, apppointments_number, deactivated_at, created_at, updated_at FROM packages WHERE id = $1
`

func (q *Queries) GetPackageById(ctx context.Context, id uuid.UUID) (*Package, error) {
	row := q.db.QueryRowContext(ctx, GetPackageById, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ProfessionalID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ApppointmentsNumber,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetPackagesByClientId = `-- name: GetPackagesByClientId :many
SELECT p.id, p.issued_at, p.expires_at, p.apppointments_number, p.deactivated_at, pr.first_name, pr.last_name
FROM packages p
LEFT JOIN professionals pr
ON pr.id = p.professional_id
WHERE client_id = $1
`

type GetPackagesByClientIdRow struct {
	ID                  uuid.UUID      `json:"id"`
	IssuedAt            time.Time      `json:"issued_at"`
	ExpiresAt           time.Time      `json:"expires_at"`
	ApppointmentsNumber int32          `json:"apppointments_number"`
	DeactivatedAt       sql.NullTime   `json:"deactivated_at"`
	FirstName           sql.NullString `json:"first_name"`
	LastName            sql.NullString `json:"last_name"`
}

func (q *Queries) GetPackagesByClientId(ctx context.Context, clientID uuid.UUID) ([]*GetPackagesByClientIdRow, error) {
	rows, err := q.db.QueryContext(ctx, GetPackagesByClientId, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPackagesByClientIdRow{}
	for rows.Next() {
		var i GetPackagesByClientIdRow
		if err := rows.Scan(
			&i.ID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.ApppointmentsNumber,
			&i.DeactivatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
