// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: professionals.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const CountProfessionalAppointmentsWithStatusAndDate = `-- name: CountProfessionalAppointmentsWithStatusAndDate :one
SELECT COUNT(*)
FROM appointments a
WHERE a.professional_id = $1
    AND ($2 = '' OR a.status = $2::appointment_status)
    AND ($3 = '' OR DATE(a.start_time) = $3::date)
    AND a.start_time > NOW()
    AND a.type != 'unavailable'
`

type CountProfessionalAppointmentsWithStatusAndDateParams struct {
	ProfessionalID uuid.UUID   `json:"professional_id"`
	Column2        interface{} `json:"column_2"`
	Column3        interface{} `json:"column_3"`
}

func (q *Queries) CountProfessionalAppointmentsWithStatusAndDate(ctx context.Context, arg *CountProfessionalAppointmentsWithStatusAndDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountProfessionalAppointmentsWithStatusAndDate, arg.ProfessionalID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountProfessionals = `-- name: CountProfessionals :one
SELECT COUNT(*) FROM professionals p
WHERE p.chat_id is not null
AND p.id NOT IN (
    SELECT DISTINCT(professional_id)
    FROM subscriptions
    WHERE client_id = $1
)
`

func (q *Queries) CountProfessionals(ctx context.Context, clientID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountProfessionals, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateGroupVisitAppointment = `-- name: CreateGroupVisitAppointment :exec
INSERT INTO appointments (type, professional_id, start_time, end_time, status, description)
VALUES ('group', $1, $2, $3, 'confirmed', $4)
`

type CreateGroupVisitAppointmentParams struct {
	ProfessionalID uuid.UUID      `json:"professional_id"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Description    sql.NullString `json:"description"`
}

func (q *Queries) CreateGroupVisitAppointment(ctx context.Context, arg *CreateGroupVisitAppointmentParams) error {
	_, err := q.db.ExecContext(ctx, CreateGroupVisitAppointment,
		arg.ProfessionalID,
		arg.StartTime,
		arg.EndTime,
		arg.Description,
	)
	return err
}

const CreateProfessional = `-- name: CreateProfessional :one
INSERT INTO professionals (username, first_name, last_name, password_hash, chat_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, chat_id, first_name, last_name, username, password_hash, locale, created_at, updated_at
`

type CreateProfessionalParams struct {
	Username     string        `json:"username"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	PasswordHash string        `json:"password_hash"`
	ChatID       sql.NullInt64 `json:"chat_id"`
}

func (q *Queries) CreateProfessional(ctx context.Context, arg *CreateProfessionalParams) (*Professional, error) {
	row := q.db.QueryRowContext(ctx, CreateProfessional,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.ChatID,
	)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetAppointmentsByProfessionalWithStatusAndDate = `-- name: GetAppointmentsByProfessionalWithStatusAndDate :many
SELECT 
    a.id,
    a.start_time,
    a.end_time,
    a.type,
    COALESCE(
        ARRAY_AGG(
            c.first_name || ' ' || c.last_name
            ORDER BY c.last_name
        ) FILTER (WHERE c.id IS NOT NULL),
        ARRAY[]::text[]
    )::text[] AS clients
FROM appointments a
LEFT JOIN client_appointments ca ON ca.appointment_id = a.id
LEFT JOIN clients c ON c.id = ca.client_id
WHERE a.professional_id = $1
  AND ($2::appointment_status IS NULL OR a.status = $2)
  AND a.start_time > NOW()
  AND a.type != 'unavailable'
GROUP BY a.id, a.start_time, a.end_time
ORDER BY a.start_time ASC
LIMIT $3 OFFSET $4
`

type GetAppointmentsByProfessionalWithStatusAndDateParams struct {
	ProfessionalID uuid.UUID `json:"professional_id"`
	Column2        string    `json:"column_2"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type GetAppointmentsByProfessionalWithStatusAndDateRow struct {
	ID        uuid.UUID `json:"id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Type      string    `json:"type"`
	Clients   []string  `json:"clients"`
}

func (q *Queries) GetAppointmentsByProfessionalWithStatusAndDate(ctx context.Context, arg *GetAppointmentsByProfessionalWithStatusAndDateParams) ([]*GetAppointmentsByProfessionalWithStatusAndDateRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAppointmentsByProfessionalWithStatusAndDate,
		arg.ProfessionalID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAppointmentsByProfessionalWithStatusAndDateRow{}
	for rows.Next() {
		var i GetAppointmentsByProfessionalWithStatusAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Type,
			pq.Array(&i.Clients),
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProfessionalByUsername = `-- name: GetProfessionalByUsername :one
SELECT id, chat_id, first_name, last_name, username, password_hash, locale, created_at, updated_at FROM professionals
WHERE username = $1
`

func (q *Queries) GetProfessionalByUsername(ctx context.Context, username string) (*Professional, error) {
	row := q.db.QueryRowContext(ctx, GetProfessionalByUsername, username)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetProfessionalClients = `-- name: GetProfessionalClients :many
SELECT id, first_name, last_name
FROM clients
WHERE id IN (
    SELECT DISTINCT(client_id)
    FROM appointments
    WHERE professional_id = $1
        AND client_id IS NOT NULL
        AND status = 'confirmed'
)
ORDER BY first_name, last_name
`

type GetProfessionalClientsRow struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) GetProfessionalClients(ctx context.Context, professionalID uuid.UUID) ([]*GetProfessionalClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetProfessionalClients, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProfessionalClientsRow{}
	for rows.Next() {
		var i GetProfessionalClientsRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProfessionalInfoForNotification = `-- name: GetProfessionalInfoForNotification :one
SELECT chat_id, locale
FROM professionals
WHERE id = $1
`

type GetProfessionalInfoForNotificationRow struct {
	ChatID sql.NullInt64 `json:"chat_id"`
	Locale string        `json:"locale"`
}

func (q *Queries) GetProfessionalInfoForNotification(ctx context.Context, id uuid.UUID) (*GetProfessionalInfoForNotificationRow, error) {
	row := q.db.QueryRowContext(ctx, GetProfessionalInfoForNotification, id)
	var i GetProfessionalInfoForNotificationRow
	err := row.Scan(&i.ChatID, &i.Locale)
	return &i, err
}

const GetProfessionalInfoForNotificationByAppointmentID = `-- name: GetProfessionalInfoForNotificationByAppointmentID :one
SELECT chat_id, locale
FROM professionals
WHERE id = (
    SELECT professional_id FROM appointments a WHERE a.id = $1
)
`

type GetProfessionalInfoForNotificationByAppointmentIDRow struct {
	ChatID sql.NullInt64 `json:"chat_id"`
	Locale string        `json:"locale"`
}

func (q *Queries) GetProfessionalInfoForNotificationByAppointmentID(ctx context.Context, id uuid.UUID) (*GetProfessionalInfoForNotificationByAppointmentIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetProfessionalInfoForNotificationByAppointmentID, id)
	var i GetProfessionalInfoForNotificationByAppointmentIDRow
	err := row.Scan(&i.ChatID, &i.Locale)
	return &i, err
}

const GetProfessionals = `-- name: GetProfessionals :many
SELECT id, first_name, last_name, chat_id, locale
FROM professionals p
WHERE p.chat_id is not null
AND p.id NOT IN (
    SELECT DISTINCT(professional_id)
    FROM subscriptions
    WHERE client_id = $1
)
ORDER BY p.first_name, p.last_name
LIMIT $2 OFFSET $3
`

type GetProfessionalsParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetProfessionalsRow struct {
	ID        uuid.UUID     `json:"id"`
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
	ChatID    sql.NullInt64 `json:"chat_id"`
	Locale    string        `json:"locale"`
}

func (q *Queries) GetProfessionals(ctx context.Context, arg *GetProfessionalsParams) ([]*GetProfessionalsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetProfessionals, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProfessionalsRow{}
	for rows.Next() {
		var i GetProfessionalsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ChatID,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProfessionalChatID = `-- name: UpdateProfessionalChatID :one
UPDATE professionals
SET chat_id = $2, locale = $3
WHERE id = $1
RETURNING id, chat_id, first_name, last_name, username, password_hash, locale, created_at, updated_at
`

type UpdateProfessionalChatIDParams struct {
	ID     uuid.UUID     `json:"id"`
	ChatID sql.NullInt64 `json:"chat_id"`
	Locale string        `json:"locale"`
}

func (q *Queries) UpdateProfessionalChatID(ctx context.Context, arg *UpdateProfessionalChatIDParams) (*Professional, error) {
	row := q.db.QueryRowContext(ctx, UpdateProfessionalChatID, arg.ID, arg.ChatID, arg.Locale)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateProfessionalLocale = `-- name: UpdateProfessionalLocale :exec
UPDATE professionals
SET locale = $2
WHERE id = $1
`

type UpdateProfessionalLocaleParams struct {
	ID     uuid.UUID `json:"id"`
	Locale string    `json:"locale"`
}

func (q *Queries) UpdateProfessionalLocale(ctx context.Context, arg *UpdateProfessionalLocaleParams) error {
	_, err := q.db.ExecContext(ctx, UpdateProfessionalLocale, arg.ID, arg.Locale)
	return err
}
