// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAppointment(ctx context.Context, arg *CreateAppointmentParams) (*Appointment, error)
	CreateAppointmentWithDetails(ctx context.Context, arg *CreateAppointmentWithDetailsParams) (*CreateAppointmentWithDetailsRow, error)
	CreateClient(ctx context.Context, arg *CreateClientParams) (*User, error)
	CreateProfessional(ctx context.Context, arg *CreateProfessionalParams) (*User, error)
	GetProfessionals(ctx context.Context) ([]*User, error)
	GetUserByChatID(ctx context.Context, chatID sql.NullInt64) (*User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	UpdateUserByUsername(ctx context.Context, arg *UpdateUserByUsernameParams) (*User, error)
	UpdateUserChatID(ctx context.Context, arg *UpdateUserChatIDParams) (*User, error)
	VerifyProfessionalCredentials(ctx context.Context, arg *VerifyProfessionalCredentialsParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
