// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CountSubscriptionsByClientID = `-- name: CountSubscriptionsByClientID :one
SELECT COUNT(*) FROM subscriptions
WHERE client_id = $1
`

func (q *Queries) CountSubscriptionsByClientID(ctx context.Context, clientID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSubscriptionsByClientID, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (client_id, professional_id)
VALUES ($1, $2)
`

type CreateSubscriptionParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	ProfessionalID uuid.UUID `json:"professional_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg *CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, CreateSubscription, arg.ClientID, arg.ProfessionalID)
	return err
}

const DeleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE client_id = $1 AND professional_id = $2
`

type DeleteSubscriptionParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	ProfessionalID uuid.UUID `json:"professional_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg *DeleteSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, DeleteSubscription, arg.ClientID, arg.ProfessionalID)
	return err
}

const GetClientSubscriptionByClientIDAndProfessionalID = `-- name: GetClientSubscriptionByClientIDAndProfessionalID :one
SELECT EXISTS(
  SELECT 1 FROM subscriptions
  WHERE client_id = $1 AND professional_id = $2
) AS exists
`

type GetClientSubscriptionByClientIDAndProfessionalIDParams struct {
	ClientID       uuid.UUID `json:"client_id"`
	ProfessionalID uuid.UUID `json:"professional_id"`
}

func (q *Queries) GetClientSubscriptionByClientIDAndProfessionalID(ctx context.Context, arg *GetClientSubscriptionByClientIDAndProfessionalIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, GetClientSubscriptionByClientIDAndProfessionalID, arg.ClientID, arg.ProfessionalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const GetSubscriptionsByClientID = `-- name: GetSubscriptionsByClientID :many
SELECT p.id, p.first_name, p.last_name, p.chat_id, p.locale FROM subscriptions s
JOIN professionals p ON s.professional_id = p.id
WHERE s.client_id = $1
ORDER BY p.first_name, p.last_name
LIMIT $2 OFFSET $3
`

type GetSubscriptionsByClientIDParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetSubscriptionsByClientIDRow struct {
	ID        uuid.UUID     `json:"id"`
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
	ChatID    sql.NullInt64 `json:"chat_id"`
	Locale    string        `json:"locale"`
}

func (q *Queries) GetSubscriptionsByClientID(ctx context.Context, arg *GetSubscriptionsByClientIDParams) ([]*GetSubscriptionsByClientIDRow, error) {
	rows, err := q.db.QueryContext(ctx, GetSubscriptionsByClientID, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetSubscriptionsByClientIDRow{}
	for rows.Next() {
		var i GetSubscriptionsByClientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ChatID,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSubscriptionsByProfessionalID = `-- name: GetSubscriptionsByProfessionalID :many
SELECT c.id, c.first_name, c.last_name, c.chat_id, c.locale FROM subscriptions s
JOIN clients c ON s.client_id = c.id
WHERE s.professional_id = $1
ORDER BY c.first_name, c.last_name
`

type GetSubscriptionsByProfessionalIDRow struct {
	ID        uuid.UUID     `json:"id"`
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
	ChatID    sql.NullInt64 `json:"chat_id"`
	Locale    string        `json:"locale"`
}

func (q *Queries) GetSubscriptionsByProfessionalID(ctx context.Context, professionalID uuid.UUID) ([]*GetSubscriptionsByProfessionalIDRow, error) {
	rows, err := q.db.QueryContext(ctx, GetSubscriptionsByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetSubscriptionsByProfessionalIDRow{}
	for rows.Next() {
		var i GetSubscriptionsByProfessionalIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ChatID,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
